### ISSUE TITLE
KeyError: props 

### ISSUE THREAD

**Issue by wjarka** [dbuezas/eq3btsmart#53] opened 2023-02-07 15:13 UTC
also a lot of those in the logs when using via Bluetooth Proxy

> This error originated from a custom integration.
> 
> Logger: homeassistant
> Source: custom_components/dbuezas_eq3btsmart/binary_sensor.py:89 
> Integration: eQ-3 Bluetooth Smart Thermostats (dbuezas) (documentation, issues) 
> First occurred: 12:19:02 PM (1123 occurrences) 
> Last logged: 4:08:11 PM
> 
> Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_update_ha_state
>     self._async_write_ha_state()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 610, in _async_write_ha_state
>     attr.update(self.extra_state_attributes or {})
>   File "/config/custom_components/dbuezas_eq3btsmart/binary_sensor.py", line 89, in extra_state_attributes
>     return json.loads(json.dumps(details["props"], default=json_serial))
> KeyError: 'props'
>

**Comment by dbuezas** [comment] 2023-02-07 17:17
Do you have the debug entities enabled?
I made those before the BTProxy worked, so it could be that something crashes in them with BTProxies

**Comment by dbuezas** [comment] 2023-02-07 17:18
Kind of a duplicate of #52

**Closed by dbuezas** 2023-02-07 17:18 UTC

**Comment by wjarka** [comment] 2023-02-07 20:13
> Do you have the debug entities enabled?
> I made those before the BTProxy worked, so it could be that something crashes in them with BTProxies

I did have debug entities enabled for two TRVs. Disabled it and will see if the issue is gone or not. Will update you tomorrow ;).

Thanks!
